# Page settings

baseurl = ""
languageCode = "zh-cn"
title = "杨超凡-简历"
theme = "hugo-orbit-theme"
googleAnalytics = ""

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Responsive Resume/CV"
    author = "Shirely Yang"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "杨超凡"
        tagline = "前端工程师"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: chaofan0926@163.com"
        title = "chaofan0926@163.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:18521370996"
        title = "18521370996"

#       [[params.contact.list]]
#        class = "website"
#        icon = "fa-globe"
#        url = "//portfoliosite.com"
#        title = "portfoliosite.com"

#        [[params.contact.list]]
#        class = "linkedin"
#        icon = "fa-linkedin"
#        url = "//linkedin.com/in/johndoe"
#        title = "linkedin.com/in/johndoe"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/Shirley0926"
        title = "github.com/Shirley0926"
#
#        [[params.contact.list]]
#        class = "twitter"
#        icon = "fa-twitter"
#        url = "//twitter.com/username"
#        title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "教育经历"

        [[params.education.list]]
        degree = "硕士"
        college = "中国海洋大学"
        dates = "2011 - 2014"

        [[params.education.list]]
        degree = "本科"
        college = "中国海洋大学"
        dates = "2007 - 2011"

    # Languages section
    [params.languages]
        enable = true
        title = "语言技能"

        [[params.languages.list]]
        language = "英语"
        level = "熟练"


    # Interests section
    [params.interests]
        enable = false
        title = "爱好"

        [[params.interests.list]]
        interest = "电影"

        [[params.interests.list]]
        interest = "音乐"

        [[params.interests.list]]
        interest = "运动"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = false
        icon = "fa-user"
        title = "个人评价"
        summary = "- 自学web前端，具有较强的学习能力，以及分析和解决问题的能力。- 待人真诚，对工作充满热情，具有较强的沟通能力，以及团队协作意识。- 适应能力强，抗压能力强，认同多元化的重要性，敢于冒险，敢于挑战新事物。"

    # Experiences section
    [params.experiences]
        enable = false
        icon = "fa-briefcase"
        title = "工作经历"

        [[params.jobs.list]]
        position = "Lead Developer"
        dates = "2015 - Present"
        company = "Startup Hubs, San Francisco"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "项目经历"
        intro = "自学前端3个月，几乎每天都在Github上有commit，主要项目来源为百度前端学院"
        url = "http://shirley0926.github.io/Baidu.IFE/"

        [[params.projects.list]]
        title = "行星与飞船"
        url = "http://shirley0926.github.io/Baidu.IFE/task28/task28.html"
        tagline = "项目来源于百度前端技术学院，目的是通过对飞船发送飞行或者自爆的指令，使其完成相应动作，并设计飞机能量逻辑，当能量耗光时自动停止并加油，加满后重新开始飞行。同时发送指令时考虑实际过程中可能发送失败的情况采用随机数进行模拟失败概率，项目使用HTML，CSS，JavaScript，JQuery完成。<br />&emsp;&emsp;负责网页的开发，包括HTML页面的设计以及利用CSS对标签元素进行布局，并且使用CSS3中的动画特性。<br />&emsp;&emsp;负责页面交互逻辑的设计开发，其中控制台输出部分采用**单例模式**避免建立重复对象，飞船部分使用**原型模式**使得创建的多个飞船实例可以使用共同的方法避免代码的重复，使用JQuery高效操作DOM并且添加相关的事件绑定。<br />&emsp;&emsp;根据**面向对象**思想，将飞船，行星，控制台分为三个类分别开发，降低耦合，利于后期维护。"

        [[params.projects.list]]
        title = "商用主页示例"
        url = "http://shirley0926.github.io/Baidu.IFE/html/task7.html"
        tagline = "根据设计师的设计文档（例如PSD），完成页面的设计和开发。<br />&emsp;&emsp;使用Photoshop进行页面的切图，形成相应的HTML文件，并将相关样式添加到对应的CSS包括伪类对应的动画样式，例如hover，focus。<br />&emsp;&emsp;对于涉及输入的部分采用对应的表单控件完成例如select，checkbox等"


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "专业技能"


        [[params.skills.list]]
        skill = "HTML & HTML5"
        level = "90%"

        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "90%"

        [[params.skills.list]]
        skill = "CSS & CSS3"
        level = "80%"

        [[params.skills.list]]
        skill = "React"
        level = "50%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "杨超凡"
